FROM python:3.7-buster

# ARG user_id
# ARG group_id

RUN apt-get update \
&& pip install --upgrade pip setuptools \
&& pip install --upgrade pip
# uninstalling TensorBoard 1.15.0+nv is making problem with 'cannot convert 0 to DType'
# RUN pip uninstall -y tensorflow
RUN pip install torch==1.10
RUN pip install tensorflow==2.4.0
RUN pip install python-dotenv==0.15.0
RUN pip install nltk==3.5
RUN pip install scikit-learn==0.24.0
# RUN pip install transformers==4.1.1
RUN pip install transformers==4.15.0
# RUN pip install datasets==1.3.0
RUN pip install datasets==1.17.0
RUN pip install seqeval==1.2.2
RUN pip install celery==5.0.5
RUN pip install flower==0.9.7
RUN pip install spacy==2.3.5
RUN pip install lxml==4.6.2
RUN pip install neo4j==4.1.1
# download language models for spacy
RUN python -m spacy download en_core_web_sm

# for running jupyter
RUN pip install notebook
# apparently needs separate installation for progress bar stuff in jupyter
# https://ipywidgets.readthedocs.io/en/stable/user_install.html
RUN pip install ipywidgets

# optional for plotting
RUN pip install plotly 

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*1

# USER $user_id:$dgroup_id
