version: '3'

services:
  smtag:
    image: tlemberger/smarttag:latest  # docker pull tlemberger/smarttag:firsthub
    volumes:
      - cache:/root/.cache
    entrypoint: ["python", "-m", "smtag.cli.inference.tag"]

volumes:
    cache:
      driver: local

